// GENERATED by tools/regen_vrchat_table.ps1. Do not edit by hand.

namespace {

std::string VRChatGeneratedVrcAnalyticsEventOptions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnalyticsEventOptions, "sdk/VRChat/VRC/Core/AnalyticsEventOptions.h");
}

std::string VRChatGeneratedVrcAnalyticsInterface() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnalyticsInterface, "sdk/VRChat/VRC/Core/AnalyticsInterface.h");
}

std::string VRChatGeneratedVrcAnalyticsSDK() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnalyticsSDK, "sdk/VRChat/VRC/Core/AnalyticsSDK.h");
}

std::string VRChatGeneratedVrcVRChatInternalAPI() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRChatInternalAPI, "sdk/VRChat/VRC/Core/Annotations/VRChatInternalAPI.h");
}

std::string VRChatGeneratedVrcAPI() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPI, "sdk/VRChat/VRC/Core/API.h");
}

std::string VRChatGeneratedVrcAPI2FA() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPI2FA, "sdk/VRChat/VRC/Core/API2FA.h");
}

std::string VRChatGeneratedVrcApiAccountUpgrade() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiAccountUpgrade, "sdk/VRChat/VRC/Core/ApiAccountUpgrade.h");
}

std::string VRChatGeneratedVrcAPIActivationSuccessfulTargetResult() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIActivationSuccessfulTargetResult, "sdk/VRChat/VRC/Core/APIActivationSuccessfulTargetResult.h");
}

std::string VRChatGeneratedVrcApiAdminAssetBundle() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiAdminAssetBundle, "sdk/VRChat/VRC/Core/ApiAdminAssetBundle.h");
}

std::string VRChatGeneratedVrcApiAdminAssetBundleFile() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiAdminAssetBundleFile, "sdk/VRChat/VRC/Core/ApiAdminAssetBundleFile.h");
}

std::string VRChatGeneratedVrcApiAuthContinue() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiAuthContinue, "sdk/VRChat/VRC/Core/ApiAuthContinue.h");
}

std::string VRChatGeneratedVrcApiAvatar() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiAvatar, "sdk/VRChat/VRC/Core/ApiAvatar.h");
}

std::string VRChatGeneratedVrcApiAvatarModeration() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiAvatarModeration, "sdk/VRChat/VRC/Core/ApiAvatarModeration.h");
}

std::string VRChatGeneratedVrcApiAvatarStyle() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiAvatarStyle, "sdk/VRChat/VRC/Core/ApiAvatarStyle.h");
}

std::string VRChatGeneratedVrcApiBadge() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiBadge, "sdk/VRChat/VRC/Core/ApiBadge.h");
}

std::string VRChatGeneratedVrcApiBindingCommandReference() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiBindingCommandReference, "sdk/VRChat/VRC/Core/ApiBindingCommandReference.h");
}

std::string VRChatGeneratedVrcApiCache() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCache, "sdk/VRChat/VRC/Core/ApiCache.h");
}

std::string VRChatGeneratedVrcApiCacheObject() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCacheObject, "sdk/VRChat/VRC/Core/ApiCacheObject.h");
}

std::string VRChatGeneratedVrcApiCalendarEntriesContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCalendarEntriesContainer, "sdk/VRChat/VRC/Core/ApiCalendarEntriesContainer.h");
}

std::string VRChatGeneratedVrcAPICalendarEntry() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPICalendarEntry, "sdk/VRChat/VRC/Core/APICalendarEntry.h");
}

std::string VRChatGeneratedVrcAPICalendarEntryUserInterest() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPICalendarEntryUserInterest, "sdk/VRChat/VRC/Core/APICalendarEntryUserInterest.h");
}

std::string VRChatGeneratedVrcApiCalendarResults() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCalendarResults, "sdk/VRChat/VRC/Core/ApiCalendarResults.h");
}

std::string VRChatGeneratedVrcApiCampaignAnonymizationStatus() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCampaignAnonymizationStatus, "sdk/VRChat/VRC/Core/ApiCampaignAnonymizationStatus.h");
}

std::string VRChatGeneratedVrcApiCampaignContributor() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCampaignContributor, "sdk/VRChat/VRC/Core/ApiCampaignContributor.h");
}

std::string VRChatGeneratedVrcAPICampaignInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPICampaignInfo, "sdk/VRChat/VRC/Core/APICampaignInfo.h");
}

std::string VRChatGeneratedVrcApiCampaignReward() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCampaignReward, "sdk/VRChat/VRC/Core/ApiCampaignReward.h");
}

std::string VRChatGeneratedVrcApiCampaignRewardProgression() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCampaignRewardProgression, "sdk/VRChat/VRC/Core/ApiCampaignRewardProgression.h");
}

std::string VRChatGeneratedVrcApiCertificateVerifier() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCertificateVerifier, "sdk/VRChat/VRC/Core/ApiCertificateVerifier.h");
}

std::string VRChatGeneratedVrcApiContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiContainer, "sdk/VRChat/VRC/Core/ApiContainer.h");
}

std::string VRChatGeneratedVrcApiCredentials() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiCredentials, "sdk/VRChat/VRC/Core/ApiCredentials.h");
}

std::string VRChatGeneratedVrcApiDictContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiDictContainer, "sdk/VRChat/VRC/Core/ApiDictContainer.h");
}

std::string VRChatGeneratedVrcApiDroneSkin() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiDroneSkin, "sdk/VRChat/VRC/Core/ApiDroneSkin.h");
}

std::string VRChatGeneratedVrcApiEconomyStatus() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiEconomyStatus, "sdk/VRChat/VRC/Core/ApiEconomyStatus.h");
}

std::string VRChatGeneratedVrcApiEconomyStore() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiEconomyStore, "sdk/VRChat/VRC/Core/ApiEconomyStore.h");
}

std::string VRChatGeneratedVrcAPIEmoji() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIEmoji, "sdk/VRChat/VRC/Core/APIEmoji.h");
}

std::string VRChatGeneratedVrcApiFieldAttribute() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiFieldAttribute, "sdk/VRChat/VRC/Core/ApiFieldAttribute.h");
}

std::string VRChatGeneratedVrcApiFile() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiFile, "sdk/VRChat/VRC/Core/ApiFile.h");
}

std::string VRChatGeneratedVrcAPIGiftBundle() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGiftBundle, "sdk/VRChat/VRC/Core/APIGiftBundle.h");
}

std::string VRChatGeneratedVrcAPIGroup() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroup, "sdk/VRChat/VRC/Core/APIGroup.h");
}

std::string VRChatGeneratedVrcAPIGroupAnnouncement() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupAnnouncement, "sdk/VRChat/VRC/Core/APIGroupAnnouncement.h");
}

std::string VRChatGeneratedVrcApiGroupGalleryImage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiGroupGalleryImage, "sdk/VRChat/VRC/Core/ApiGroupGalleryImage.h");
}

std::string VRChatGeneratedVrcAPIGroupInvite() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupInvite, "sdk/VRChat/VRC/Core/APIGroupInvite.h");
}

std::string VRChatGeneratedVrcAPIGroupJoinResponse() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupJoinResponse, "sdk/VRChat/VRC/Core/APIGroupJoinResponse.h");
}

std::string VRChatGeneratedVrcAPIGroupList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupList, "sdk/VRChat/VRC/Core/APIGroupList.h");
}

std::string VRChatGeneratedVrcAPIGroupLocations() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupLocations, "sdk/VRChat/VRC/Core/APIGroupLocations.h");
}

std::string VRChatGeneratedVrcAPIGroupMember() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupMember, "sdk/VRChat/VRC/Core/APIGroupMember.h");
}

std::string VRChatGeneratedVrcAPIGroupMemberList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupMemberList, "sdk/VRChat/VRC/Core/APIGroupMemberList.h");
}

std::string VRChatGeneratedVrcAPIGroupPosts() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupPosts, "sdk/VRChat/VRC/Core/APIGroupPosts.h");
}

std::string VRChatGeneratedVrcAPIGroupRole() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupRole, "sdk/VRChat/VRC/Core/APIGroupRole.h");
}

std::string VRChatGeneratedVrcAPIGroupRoleList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIGroupRoleList, "sdk/VRChat/VRC/Core/APIGroupRoleList.h");
}

std::string VRChatGeneratedVrcApiImage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiImage, "sdk/VRChat/VRC/Core/ApiImage.h");
}

std::string VRChatGeneratedVrcApiInfoPushSystem() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiInfoPushSystem, "sdk/VRChat/VRC/Core/ApiInfoPushSystem.h");
}

std::string VRChatGeneratedVrcApiInventoryBundle() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiInventoryBundle, "sdk/VRChat/VRC/Core/ApiInventoryBundle.h");
}

std::string VRChatGeneratedVrcApiInventoryBundleDrop() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiInventoryBundleDrop, "sdk/VRChat/VRC/Core/ApiInventoryBundleDrop.h");
}

std::string VRChatGeneratedVrcApiInventoryItem() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiInventoryItem, "sdk/VRChat/VRC/Core/ApiInventoryItem.h");
}

std::string VRChatGeneratedVrcApiInventoryItemContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiInventoryItemContainer, "sdk/VRChat/VRC/Core/ApiInventoryItemContainer.h");
}

std::string VRChatGeneratedVrcApiInventoryJweToken() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiInventoryJweToken, "sdk/VRChat/VRC/Core/ApiInventoryJweToken.h");
}

std::string VRChatGeneratedVrcApiLedgerTransaction() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiLedgerTransaction, "sdk/VRChat/VRC/Core/ApiLedgerTransaction.h");
}

std::string VRChatGeneratedVrcApiLedgerTransactions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiLedgerTransactions, "sdk/VRChat/VRC/Core/ApiLedgerTransactions.h");
}

std::string VRChatGeneratedVrcApiLicense() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiLicense, "sdk/VRChat/VRC/Core/ApiLicense.h");
}

std::string VRChatGeneratedVrcApiLicenseNote() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiLicenseNote, "sdk/VRChat/VRC/Core/ApiLicenseNote.h");
}

std::string VRChatGeneratedVrcApiListContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiListContainer, "sdk/VRChat/VRC/Core/ApiListContainer.h");
}

std::string VRChatGeneratedVrcApiLocalizableString() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiLocalizableString, "sdk/VRChat/VRC/Core/ApiLocalizableString.h");
}

std::string VRChatGeneratedVrcApiMessage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiMessage, "sdk/VRChat/VRC/Core/ApiMessage.h");
}

std::string VRChatGeneratedVrcApiModel() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiModel, "sdk/VRChat/VRC/Core/ApiModel.h");
}

std::string VRChatGeneratedVrcApiModeration() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiModeration, "sdk/VRChat/VRC/Core/ApiModeration.h");
}

std::string VRChatGeneratedVrcApiMutualFriend() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiMutualFriend, "sdk/VRChat/VRC/Core/ApiMutualFriend.h");
}

std::string VRChatGeneratedVrcApiMutualGroup() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiMutualGroup, "sdk/VRChat/VRC/Core/ApiMutualGroup.h");
}

std::string VRChatGeneratedVrcApiNotification() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiNotification, "sdk/VRChat/VRC/Core/ApiNotification.h");
}

std::string VRChatGeneratedVrcApiOnlineMode() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiOnlineMode, "sdk/VRChat/VRC/Core/ApiOnlineMode.h");
}

std::string VRChatGeneratedVrcApiPagedTransactions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPagedTransactions, "sdk/VRChat/VRC/Core/ApiPagedTransactions.h");
}

std::string VRChatGeneratedVrcApiPendingTransaction() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPendingTransaction, "sdk/VRChat/VRC/Core/ApiPendingTransaction.h");
}

std::string VRChatGeneratedVrcApiPlayerModeration() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPlayerModeration, "sdk/VRChat/VRC/Core/ApiPlayerModeration.h");
}

std::string VRChatGeneratedVrcApiPortalSkin() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPortalSkin, "sdk/VRChat/VRC/Core/ApiPortalSkin.h");
}

std::string VRChatGeneratedVrcApiPrint() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPrint, "sdk/VRChat/VRC/Core/ApiPrint.h");
}

std::string VRChatGeneratedVrcApiProduct() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiProduct, "sdk/VRChat/VRC/Core/ApiProduct.h");
}

std::string VRChatGeneratedVrcAPIProductGiftingCheck() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIProductGiftingCheck, "sdk/VRChat/VRC/Core/APIProductGiftingCheck.h");
}

std::string VRChatGeneratedVrcApiProductPurchaseStatus() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiProductPurchaseStatus, "sdk/VRChat/VRC/Core/ApiProductPurchaseStatus.h");
}

std::string VRChatGeneratedVrcApiProductVariant() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiProductVariant, "sdk/VRChat/VRC/Core/ApiProductVariant.h");
}

std::string VRChatGeneratedVrcApiProp() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiProp, "sdk/VRChat/VRC/Core/ApiProp.h");
}

std::string VRChatGeneratedVrcApiPropItemMetadata() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPropItemMetadata, "sdk/VRChat/VRC/Core/ApiPropItemMetadata.h");
}

std::string VRChatGeneratedVrcApiPurchase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPurchase, "sdk/VRChat/VRC/Core/ApiPurchase.h");
}

std::string VRChatGeneratedVrcApiPurchaseCancelSubscriptionInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPurchaseCancelSubscriptionInfo, "sdk/VRChat/VRC/Core/ApiPurchaseCancelSubscriptionInfo.h");
}

std::string VRChatGeneratedVrcAPIPurchasedGiftBundle() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIPurchasedGiftBundle, "sdk/VRChat/VRC/Core/APIPurchasedGiftBundle.h");
}

std::string VRChatGeneratedVrcApiPurchaseSubscriptionCancelledInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiPurchaseSubscriptionCancelledInfo, "sdk/VRChat/VRC/Core/ApiPurchaseSubscriptionCancelledInfo.h");
}

std::string VRChatGeneratedVrcAPIQueue() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIQueue, "sdk/VRChat/VRC/Core/APIQueue.h");
}

std::string VRChatGeneratedVrcApiReport() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiReport, "sdk/VRChat/VRC/Core/ApiReport.h");
}

std::string VRChatGeneratedVrcApiReportDetails() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiReportDetails, "sdk/VRChat/VRC/Core/ApiReportDetails.h");
}

std::string VRChatGeneratedVrcApiReportResponse() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiReportResponse, "sdk/VRChat/VRC/Core/ApiReportResponse.h");
}

std::string VRChatGeneratedVrcApiReportsContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiReportsContainer, "sdk/VRChat/VRC/Core/ApiReportsContainer.h");
}

std::string VRChatGeneratedVrcAPIResponseHandler() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIResponseHandler, "sdk/VRChat/VRC/Core/APIResponseHandler.h");
}

std::string VRChatGeneratedVrcApiSearchGroupResults() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSearchGroupResults, "sdk/VRChat/VRC/Core/ApiSearchGroupResults.h");
}

std::string VRChatGeneratedVrcApiSearchUserResults() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSearchUserResults, "sdk/VRChat/VRC/Core/ApiSearchUserResults.h");
}

std::string VRChatGeneratedVrcApiSearchWorldResults() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSearchWorldResults, "sdk/VRChat/VRC/Core/ApiSearchWorldResults.h");
}

std::string VRChatGeneratedVrcApiServerEnvironment() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiServerEnvironment, "sdk/VRChat/VRC/Core/ApiServerEnvironment.h");
}

std::string VRChatGeneratedVrcApiSharedConnectionCounts() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSharedConnectionCounts, "sdk/VRChat/VRC/Core/ApiSharedConnectionCounts.h");
}

std::string VRChatGeneratedVrcApiSteamVRChatFinalizeTransactionResponse() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSteamVRChatFinalizeTransactionResponse, "sdk/VRChat/VRC/Core/ApiSteamVRChatFinalizeTransactionResponse.h");
}

std::string VRChatGeneratedVrcApiSteamVRChatSubscriptionSteamTransaction() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSteamVRChatSubscriptionSteamTransaction, "sdk/VRChat/VRC/Core/ApiSteamVRChatSubscriptionSteamTransaction.h");
}

std::string VRChatGeneratedVrcApiSteamVRChatSubscriptionTransaction() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSteamVRChatSubscriptionTransaction, "sdk/VRChat/VRC/Core/ApiSteamVRChatSubscriptionTransaction.h");
}

std::string VRChatGeneratedVrcApiSteamVRChatSubscriptionWalletInformation() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiSteamVRChatSubscriptionWalletInformation, "sdk/VRChat/VRC/Core/ApiSteamVRChatSubscriptionWalletInformation.h");
}

std::string VRChatGeneratedVrcAPISticker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPISticker, "sdk/VRChat/VRC/Core/APISticker.h");
}

std::string VRChatGeneratedVrcApiStoreShelf() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiStoreShelf, "sdk/VRChat/VRC/Core/ApiStoreShelf.h");
}

std::string VRChatGeneratedVrcApiStringContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiStringContainer, "sdk/VRChat/VRC/Core/ApiStringContainer.h");
}

std::string VRChatGeneratedVrcAPISubscription() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPISubscription, "sdk/VRChat/VRC/Core/APISubscription.h");
}

std::string VRChatGeneratedVrcApiTokenBundle() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiTokenBundle, "sdk/VRChat/VRC/Core/ApiTokenBundle.h");
}

std::string VRChatGeneratedVrcApiTransaction() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiTransaction, "sdk/VRChat/VRC/Core/ApiTransaction.h");
}

std::string VRChatGeneratedVrcAPITutorial() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPITutorial, "sdk/VRChat/VRC/Core/APITutorial.h");
}

std::string VRChatGeneratedVrcAPIUIColorPalette() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIUIColorPalette, "sdk/VRChat/VRC/Core/APIUIColorPalette.h");
}

std::string VRChatGeneratedVrcApiUserIcon() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiUserIcon, "sdk/VRChat/VRC/Core/ApiUserIcon.h");
}

std::string VRChatGeneratedVrcApiUserPermission() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiUserPermission, "sdk/VRChat/VRC/Core/ApiUserPermission.h");
}

std::string VRChatGeneratedVrcApiUserPermissions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiUserPermissions, "sdk/VRChat/VRC/Core/ApiUserPermissions.h");
}

std::string VRChatGeneratedVrcApiUserPlatformList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiUserPlatformList, "sdk/VRChat/VRC/Core/ApiUserPlatformList.h");
}

std::string VRChatGeneratedVrcApiUserPlatforms() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiUserPlatforms, "sdk/VRChat/VRC/Core/ApiUserPlatforms.h");
}

std::string VRChatGeneratedVrcApiViewfinderSkin() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiViewfinderSkin, "sdk/VRChat/VRC/Core/ApiViewfinderSkin.h");
}

std::string VRChatGeneratedVrcApiVRChatAdminSubscriptionTransaction() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiVRChatAdminSubscriptionTransaction, "sdk/VRChat/VRC/Core/ApiVRChatAdminSubscriptionTransaction.h");
}

std::string VRChatGeneratedVrcApiVRChatProductDetails() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiVRChatProductDetails, "sdk/VRChat/VRC/Core/ApiVRChatProductDetails.h");
}

std::string VRChatGeneratedVrcApiVRChatSubscription() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiVRChatSubscription, "sdk/VRChat/VRC/Core/ApiVRChatSubscription.h");
}

std::string VRChatGeneratedVrcApiVRChatSubscriptionBaseResponse() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiVRChatSubscriptionBaseResponse, "sdk/VRChat/VRC/Core/ApiVRChatSubscriptionBaseResponse.h");
}

std::string VRChatGeneratedVrcApiVRChatSubscriptionError() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiVRChatSubscriptionError, "sdk/VRChat/VRC/Core/ApiVRChatSubscriptionError.h");
}

std::string VRChatGeneratedVrcApiWarpEffectSkin() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiWarpEffectSkin, "sdk/VRChat/VRC/Core/ApiWarpEffectSkin.h");
}

std::string VRChatGeneratedVrcApiWorld() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiWorld, "sdk/VRChat/VRC/Core/ApiWorld.h");
}

std::string VRChatGeneratedVrcApiWorldInstance() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcApiWorldInstance, "sdk/VRChat/VRC/Core/ApiWorldInstance.h");
}

std::string VRChatGeneratedVrcAreaBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAreaBase, "sdk/VRChat/VRC/Core/AreaBase.h");
}

std::string VRChatGeneratedVrcAssetVersion() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAssetVersion, "sdk/VRChat/VRC/Core/AssetVersion.h");
}

std::string VRChatGeneratedVrcBaseConfig() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcBaseConfig, "sdk/VRChat/VRC/Core/BaseConfig.h");
}

std::string VRChatGeneratedVrcDisposableJobHandle() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDisposableJobHandle, "sdk/VRChat/VRC/Core/Burst/DisposableJobHandle.h");
}

std::string VRChatGeneratedVrcStackedCamera() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcStackedCamera, "sdk/VRChat/VRC/Core/CameraSystems/StackedCamera.h");
}

std::string VRChatGeneratedVrcCaptchaArea() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCaptchaArea, "sdk/VRChat/VRC/Core/CaptchaArea.h");
}

std::string VRChatGeneratedVrcIReadOnlyConfig() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIReadOnlyConfig, "sdk/VRChat/VRC/Core/Config/Interfaces/IReadOnlyConfig.h");
}

std::string VRChatGeneratedVrcIReadWriteConfig() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIReadWriteConfig, "sdk/VRChat/VRC/Core/Config/Interfaces/IReadWriteConfig.h");
}

std::string VRChatGeneratedVrcDiscordAccessTokenResponse() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDiscordAccessTokenResponse, "sdk/VRChat/VRC/Core/DiscordAccessTokenResponse.h");
}

std::string VRChatGeneratedVrcDiscordDeviceCodeResponse() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDiscordDeviceCodeResponse, "sdk/VRChat/VRC/Core/DiscordDeviceCodeResponse.h");
}

std::string VRChatGeneratedVrcExtensionMethods() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcExtensionMethods, "sdk/VRChat/VRC/Core/ExtensionMethods.h");
}

std::string VRChatGeneratedVrcFavoriteArea() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFavoriteArea, "sdk/VRChat/VRC/Core/FavoriteArea.h");
}

std::string VRChatGeneratedVrcFavoriteListModel() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFavoriteListModel, "sdk/VRChat/VRC/Core/FavoriteListModel.h");
}

std::string VRChatGeneratedVrcFavoriteModel() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFavoriteModel, "sdk/VRChat/VRC/Core/FavoriteModel.h");
}

std::string VRChatGeneratedVrcFavoritePrivacy() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFavoritePrivacy, "sdk/VRChat/VRC/Core/FavoritePrivacy.h");
}

std::string VRChatGeneratedVrcFavoritePrivacyExtensions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFavoritePrivacyExtensions, "sdk/VRChat/VRC/Core/FavoritePrivacyExtensions.h");
}

std::string VRChatGeneratedVrcFavoriteType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFavoriteType, "sdk/VRChat/VRC/Core/FavoriteType.h");
}

std::string VRChatGeneratedVrcFavoriteTypeExtensions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFavoriteTypeExtensions, "sdk/VRChat/VRC/Core/FavoriteTypeExtensions.h");
}

std::string VRChatGeneratedVrcGroupInstanceAccessType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcGroupInstanceAccessType, "sdk/VRChat/VRC/Core/GroupInstanceAccessType.h");
}

std::string VRChatGeneratedVrcIBundleSignatureHolder() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIBundleSignatureHolder, "sdk/VRChat/VRC/Core/IBundleSignatureHolder.h");
}

std::string VRChatGeneratedVrcILoggerReceiver() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcILoggerReceiver, "sdk/VRChat/VRC/Core/ILoggerReceiver.h");
}

std::string VRChatGeneratedVrcInstanceAccessType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInstanceAccessType, "sdk/VRChat/VRC/Core/InstanceAccessType.h");
}

std::string VRChatGeneratedVrcInstanceAccessTypeExtensions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInstanceAccessTypeExtensions, "sdk/VRChat/VRC/Core/InstanceAccessTypeExtensions.h");
}

std::string VRChatGeneratedVrcIVRCLogger() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRCLogger, "sdk/VRChat/VRC/Core/IVRCLogger.h");
}

std::string VRChatGeneratedVrcLicenseType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLicenseType, "sdk/VRChat/VRC/Core/LicenseType.h");
}

std::string VRChatGeneratedVrcListingType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcListingType, "sdk/VRChat/VRC/Core/ListingType.h");
}

std::string VRChatGeneratedVrcLocalConfig() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLocalConfig, "sdk/VRChat/VRC/Core/LocalConfig.h");
}

std::string VRChatGeneratedVrcLoggingMode() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLoggingMode, "sdk/VRChat/VRC/Core/LoggingMode.h");
}

std::string VRChatGeneratedVrcAbstractObjectStateManager() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAbstractObjectStateManager, "sdk/VRChat/VRC/Core/Networking/Codec/StateManagement/AbstractObjectStateManager.h");
}

std::string VRChatGeneratedVrcPersistenceObjectStateManager() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPersistenceObjectStateManager, "sdk/VRChat/VRC/Core/Networking/Codec/StateManagement/PersistenceObjectStateManager.h");
}

std::string VRChatGeneratedVrcSimpleObjectStateManager() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcSimpleObjectStateManager, "sdk/VRChat/VRC/Core/Networking/Codec/StateManagement/SimpleObjectStateManager.h");
}

std::string VRChatGeneratedVrcDecodeParameters32() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDecodeParameters32, "sdk/VRChat/VRC/Core/Networking/DecodeParameters32.h");
}

std::string VRChatGeneratedVrcDecodeParameters8() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDecodeParameters8, "sdk/VRChat/VRC/Core/Networking/DecodeParameters8.h");
}

std::string VRChatGeneratedVrcFixedByteBufferAllocator32() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFixedByteBufferAllocator32, "sdk/VRChat/VRC/Core/Networking/FixedByteBufferAllocator32.h");
}

std::string VRChatGeneratedVrcFixedByteBufferAllocator8() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFixedByteBufferAllocator8, "sdk/VRChat/VRC/Core/Networking/FixedByteBufferAllocator8.h");
}

std::string VRChatGeneratedVrcFlatBufferConfig() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFlatBufferConfig, "sdk/VRChat/VRC/Core/Networking/FlatBufferConfig.h");
}

std::string VRChatGeneratedVrcFlatBufferSerializerCodec() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFlatBufferSerializerCodec, "sdk/VRChat/VRC/Core/Networking/FlatBufferSerializerCodec.h");
}

std::string VRChatGeneratedVrcIEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIEvent, "sdk/VRChat/VRC/Core/Networking/IEvent.h");
}

std::string VRChatGeneratedVrcIFlatBufferNetworkSerializer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIFlatBufferNetworkSerializer, "sdk/VRChat/VRC/Core/Networking/IFlatBufferNetworkSerializer.h");
}

std::string VRChatGeneratedVrcILoggableClass() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcILoggableClass, "sdk/VRChat/VRC/Core/Networking/ILoggableClass.h");
}

std::string VRChatGeneratedVrcINetworkReadyReceiver() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcINetworkReadyReceiver, "sdk/VRChat/VRC/Core/Networking/INetworkReadyReceiver.h");
}

std::string VRChatGeneratedVrcISyncPhysics() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcISyncPhysics, "sdk/VRChat/VRC/Core/Networking/ISyncPhysics.h");
}

std::string VRChatGeneratedVrcITimedValue() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcITimedValue, "sdk/VRChat/VRC/Core/Networking/ITimedValue.h");
}

std::string VRChatGeneratedVrcITweenableValue() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcITweenableValue, "sdk/VRChat/VRC/Core/Networking/ITweenableValue.h");
}

std::string VRChatGeneratedVrcIVRC_FlatBufferSerializer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRC_FlatBufferSerializer, "sdk/VRChat/VRC/Core/Networking/IVRC_FlatBufferSerializer.h");
}

std::string VRChatGeneratedVrcIVRC_PersistentSerializer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRC_PersistentSerializer, "sdk/VRChat/VRC/Core/Networking/IVRC_PersistentSerializer.h");
}

std::string VRChatGeneratedVrcNetworkUpdateRates() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkUpdateRates, "sdk/VRChat/VRC/Core/Networking/NetworkUpdateRates.h");
}

std::string VRChatGeneratedVrcNumericExtensions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNumericExtensions, "sdk/VRChat/VRC/Core/Networking/NumericExtensions.h");
}

std::string VRChatGeneratedVrcConfiguration() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcConfiguration, "sdk/VRChat/VRC/Core/Networking/Pose/Configuration.h");
}

std::string VRChatGeneratedVrcDirectQuantizedPose() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDirectQuantizedPose, "sdk/VRChat/VRC/Core/Networking/Pose/DirectQuantizedPose.h");
}

std::string VRChatGeneratedVrcIPoseRecorder() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIPoseRecorder, "sdk/VRChat/VRC/Core/Networking/Pose/IPoseRecorder.h");
}

std::string VRChatGeneratedVrcPoseContents() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPoseContents, "sdk/VRChat/VRC/Core/Networking/Pose/PoseContents.h");
}

std::string VRChatGeneratedVrcPoseEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPoseEvent, "sdk/VRChat/VRC/Core/Networking/Pose/PoseEvent.h");
}

std::string VRChatGeneratedVrcQuantizedPose() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcQuantizedPose, "sdk/VRChat/VRC/Core/Networking/Pose/QuantizedPose.h");
}

std::string VRChatGeneratedVrcPositionEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPositionEvent, "sdk/VRChat/VRC/Core/Networking/PositionEvent.h");
}

std::string VRChatGeneratedVrcQuantizedSerialization() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcQuantizedSerialization, "sdk/VRChat/VRC/Core/Networking/QuantizedSerialization.h");
}

std::string VRChatGeneratedVrcRoomNetworkProperty() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcRoomNetworkProperty, "sdk/VRChat/VRC/Core/Networking/RoomNetworkProperty.h");
}

std::string VRChatGeneratedVrcTimeProxy() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTimeProxy, "sdk/VRChat/VRC/Core/Networking/TimeProxy.h");
}

std::string VRChatGeneratedVrcBitConverterSpan() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcBitConverterSpan, "sdk/VRChat/VRC/Core/Networking/Tools/BitConverterSpan.h");
}

std::string VRChatGeneratedVrcBunchCollection() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcBunchCollection, "sdk/VRChat/VRC/Core/Networking/Tools/BunchCollection.h");
}

std::string VRChatGeneratedVrcByteManipulation() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcByteManipulation, "sdk/VRChat/VRC/Core/Networking/Tools/ByteManipulation.h");
}

std::string VRChatGeneratedVrcHash() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcHash, "sdk/VRChat/VRC/Core/Networking/Tools/Hash.h");
}

std::string VRChatGeneratedVrcAnimationEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimationEvent, "sdk/VRChat/VRC/Core/Networking/Tween/AnimationEvent.h");
}

std::string VRChatGeneratedVrcAnimatorEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimatorEvent, "sdk/VRChat/VRC/Core/Networking/Tween/AnimatorEvent.h");
}

std::string VRChatGeneratedVrcTweenFunctions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTweenFunctions, "sdk/VRChat/VRC/Core/Networking/Tween/TweenFunctions.h");
}

std::string VRChatGeneratedVrcVRCNetworkBehaviourTypeId() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCNetworkBehaviourTypeId, "sdk/VRChat/VRC/Core/Networking/VRCNetworkBehaviourTypeId.h");
}

std::string VRChatGeneratedVrcVRCPhotonEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPhotonEvent, "sdk/VRChat/VRC/Core/Networking/VRCPhotonEvent.h");
}

std::string VRChatGeneratedVrcNetworkRegion() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkRegion, "sdk/VRChat/VRC/Core/NetworkRegion.h");
}

std::string VRChatGeneratedVrcNetworkRegionExtensions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkRegionExtensions, "sdk/VRChat/VRC/Core/NetworkRegionExtensions.h");
}

std::string VRChatGeneratedVrcNullLogger() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNullLogger, "sdk/VRChat/VRC/Core/NullLogger.h");
}

std::string VRChatGeneratedVrcPagedApiCalendarResult() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPagedApiCalendarResult, "sdk/VRChat/VRC/Core/PagedApiCalendarResult.h");
}

std::string VRChatGeneratedVrcPagedApiGroupResult() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPagedApiGroupResult, "sdk/VRChat/VRC/Core/PagedApiGroupResult.h");
}

std::string VRChatGeneratedVrcProductType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcProductType, "sdk/VRChat/VRC/Core/ProductType.h");
}

std::string VRChatGeneratedVrcRemoteConfig() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcRemoteConfig, "sdk/VRChat/VRC/Core/RemoteConfig.h");
}

std::string VRChatGeneratedVrcAPIEventSource() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIEventSource, "sdk/VRChat/VRC/Core/Services/APIEventSource.h");
}

std::string VRChatGeneratedVrcAPIEventSourceMethods() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAPIEventSourceMethods, "sdk/VRChat/VRC/Core/Services/APIEventSourceMethods.h");
}

std::string VRChatGeneratedVrcAvatarsService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAvatarsService, "sdk/VRChat/VRC/Core/Services/AvatarsService.h");
}

std::string VRChatGeneratedVrcEconomyService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcEconomyService, "sdk/VRChat/VRC/Core/Services/EconomyService.h");
}

std::string VRChatGeneratedVrcEventsService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcEventsService, "sdk/VRChat/VRC/Core/Services/EventsService.h");
}

std::string VRChatGeneratedVrcGroupsService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcGroupsService, "sdk/VRChat/VRC/Core/Services/GroupsService.h");
}

std::string VRChatGeneratedVrcIAvatarsService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIAvatarsService, "sdk/VRChat/VRC/Core/Services/IAvatarsService.h");
}

std::string VRChatGeneratedVrcIEventsService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIEventsService, "sdk/VRChat/VRC/Core/Services/IEventsService.h");
}

std::string VRChatGeneratedVrcIGroupsService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIGroupsService, "sdk/VRChat/VRC/Core/Services/IGroupsService.h");
}

std::string VRChatGeneratedVrcStoresService() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcStoresService, "sdk/VRChat/VRC/Core/Services/StoresService.h");
}

std::string VRChatGeneratedVrcNoAllocByteSetStorage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNoAllocByteSetStorage, "sdk/VRChat/VRC/Core/Source/Config/NoAllocByteSetStorage.h");
}

std::string VRChatGeneratedVrcTimeInterval() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTimeInterval, "sdk/VRChat/VRC/Core/TimeInterval.h");
}

std::string VRChatGeneratedVrcIUdonAnalyticsEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIUdonAnalyticsEvent, "sdk/VRChat/VRC/Core/UdonAnalytics/IUdonAnalyticsEvent.h");
}

std::string VRChatGeneratedVrcUdonAnalyticsCache() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUdonAnalyticsCache, "sdk/VRChat/VRC/Core/UdonAnalytics/UdonAnalyticsCache.h");
}

std::string VRChatGeneratedVrcUdonAnalyticsEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUdonAnalyticsEvent, "sdk/VRChat/VRC/Core/UdonAnalytics/UdonAnalyticsEvent.h");
}

std::string VRChatGeneratedVrcUpdateDelegator() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUpdateDelegator, "sdk/VRChat/VRC/Core/UpdateDelegator.h");
}

std::string VRChatGeneratedVrcUrlAllowlistConfig() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUrlAllowlistConfig, "sdk/VRChat/VRC/Core/UrlAllowlistConfig.h");
}

std::string VRChatGeneratedVrcVRCEvent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCEvent, "sdk/VRChat/VRC/Core/VRCEvent.h");
}

std::string VRChatGeneratedVrcVRChatTestProtocol() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRChatTestProtocol, "sdk/VRChat/VRC/Core/VRChatTestProtocol.h");
}

std::string VRChatGeneratedVrcVTP_PacketID() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVTP_PacketID, "sdk/VRChat/VRC/Core/VTP_PacketID.h");
}

std::string VRChatGeneratedVrcZLoggerHandlerLogger() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcZLoggerHandlerLogger, "sdk/VRChat/VRC/Core/ZLoggerHandlerLogger.h");
}

std::string VRChatGeneratedVrcAimVRCConstraintBinding() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAimVRCConstraintBinding, "sdk/VRChat/VRC/Dynamics/AimVRCConstraintBinding.h");
}

std::string VRChatGeneratedVrcAnimParameterAccessAvatarSDK() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimParameterAccessAvatarSDK, "sdk/VRChat/VRC/Dynamics/AnimParameterAccessAvatarSDK.h");
}

std::string VRChatGeneratedVrcBoneBuffer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcBoneBuffer, "sdk/VRChat/VRC/Dynamics/BoneBuffer.h");
}

std::string VRChatGeneratedVrcChainBuffer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcChainBuffer, "sdk/VRChat/VRC/Dynamics/ChainBuffer.h");
}

std::string VRChatGeneratedVrcChainId() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcChainId, "sdk/VRChat/VRC/Dynamics/ChainId.h");
}

std::string VRChatGeneratedVrcCollisionBroadphase_HashGrid() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCollisionBroadphase_HashGrid, "sdk/VRChat/VRC/Dynamics/CollisionBroadphase_HashGrid.h");
}

std::string VRChatGeneratedVrcCollisionBroadphase_HybridSAP() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCollisionBroadphase_HybridSAP, "sdk/VRChat/VRC/Dynamics/CollisionBroadphase_HybridSAP.h");
}

std::string VRChatGeneratedVrcCollisionScene() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCollisionScene, "sdk/VRChat/VRC/Dynamics/CollisionScene.h");
}

std::string VRChatGeneratedVrcCollisionShapes() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCollisionShapes, "sdk/VRChat/VRC/Dynamics/CollisionShapes.h");
}

std::string VRChatGeneratedVrcContactBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactBase, "sdk/VRChat/VRC/Dynamics/ContactBase.h");
}

std::string VRChatGeneratedVrcContactEnterInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactEnterInfo, "sdk/VRChat/VRC/Dynamics/ContactEnterInfo.h");
}

std::string VRChatGeneratedVrcContactExitInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactExitInfo, "sdk/VRChat/VRC/Dynamics/ContactExitInfo.h");
}

std::string VRChatGeneratedVrcContactManager() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactManager, "sdk/VRChat/VRC/Dynamics/ContactManager.h");
}

std::string VRChatGeneratedVrcContactReceiver() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactReceiver, "sdk/VRChat/VRC/Dynamics/ContactReceiver.h");
}

std::string VRChatGeneratedVrcContactReceiverProxy() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactReceiverProxy, "sdk/VRChat/VRC/Dynamics/ContactReceiverProxy.h");
}

std::string VRChatGeneratedVrcContactSender() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactSender, "sdk/VRChat/VRC/Dynamics/ContactSender.h");
}

std::string VRChatGeneratedVrcContactSenderProxy() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcContactSenderProxy, "sdk/VRChat/VRC/Dynamics/ContactSenderProxy.h");
}

std::string VRChatGeneratedVrcDynamicsComponent() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDynamicsComponent, "sdk/VRChat/VRC/Dynamics/DynamicsComponent.h");
}

std::string VRChatGeneratedVrcDynamicsUsage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDynamicsUsage, "sdk/VRChat/VRC/Dynamics/DynamicsUsage.h");
}

std::string VRChatGeneratedVrcDynamicsUsageFlags() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDynamicsUsageFlags, "sdk/VRChat/VRC/Dynamics/DynamicsUsageFlags.h");
}

std::string VRChatGeneratedVrcDynamicsUsageFlagsExtensions() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDynamicsUsageFlagsExtensions, "sdk/VRChat/VRC/Dynamics/DynamicsUsageFlagsExtensions.h");
}

std::string VRChatGeneratedVrcFixedTransformAccessArray() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcFixedTransformAccessArray, "sdk/VRChat/VRC/Dynamics/FixedTransformAccessArray.h");
}

std::string VRChatGeneratedVrcICollisionBroadphase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcICollisionBroadphase, "sdk/VRChat/VRC/Dynamics/ICollisionBroadphase.h");
}

std::string VRChatGeneratedVrcIContactReceiverUdonEmitter() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIContactReceiverUdonEmitter, "sdk/VRChat/VRC/Dynamics/IContactReceiverUdonEmitter.h");
}

std::string VRChatGeneratedVrcIMemoryBufferList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIMemoryBufferList, "sdk/VRChat/VRC/Dynamics/IMemoryBufferList.h");
}

std::string VRChatGeneratedVrcIMemoryBufferSpanList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIMemoryBufferSpanList, "sdk/VRChat/VRC/Dynamics/IMemoryBufferSpanList.h");
}

std::string VRChatGeneratedVrcIParameterSetup() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIParameterSetup, "sdk/VRChat/VRC/Dynamics/IParameterSetup.h");
}

std::string VRChatGeneratedVrcIPhysBoneDebugDrawer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIPhysBoneDebugDrawer, "sdk/VRChat/VRC/Dynamics/IPhysBoneDebugDrawer.h");
}

std::string VRChatGeneratedVrcIPhysBoneUdonEmitter() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIPhysBoneUdonEmitter, "sdk/VRChat/VRC/Dynamics/IPhysBoneUdonEmitter.h");
}

std::string VRChatGeneratedVrcIVRCConstraintBinding() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRCConstraintBinding, "sdk/VRChat/VRC/Dynamics/IVRCConstraintBinding.h");
}

std::string VRChatGeneratedVrcLookAtVRCConstraintBinding() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLookAtVRCConstraintBinding, "sdk/VRChat/VRC/Dynamics/LookAtVRCConstraintBinding.h");
}

std::string VRChatGeneratedVrcVRCAimConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCAimConstraintBase, "sdk/VRChat/VRC/Dynamics/ManagedTypes/VRCAimConstraintBase.h");
}

std::string VRChatGeneratedVrcVRCLookAtConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCLookAtConstraintBase, "sdk/VRChat/VRC/Dynamics/ManagedTypes/VRCLookAtConstraintBase.h");
}

std::string VRChatGeneratedVrcVRCParentConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCParentConstraintBase, "sdk/VRChat/VRC/Dynamics/ManagedTypes/VRCParentConstraintBase.h");
}

std::string VRChatGeneratedVrcVRCPositionConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPositionConstraintBase, "sdk/VRChat/VRC/Dynamics/ManagedTypes/VRCPositionConstraintBase.h");
}

std::string VRChatGeneratedVrcVRCRotationConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCRotationConstraintBase, "sdk/VRChat/VRC/Dynamics/ManagedTypes/VRCRotationConstraintBase.h");
}

std::string VRChatGeneratedVrcVRCScaleConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCScaleConstraintBase, "sdk/VRChat/VRC/Dynamics/ManagedTypes/VRCScaleConstraintBase.h");
}

std::string VRChatGeneratedVrcVRCWorldUpConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCWorldUpConstraintBase, "sdk/VRChat/VRC/Dynamics/ManagedTypes/VRCWorldUpConstraintBase.h");
}

std::string VRChatGeneratedVrcMathUtil() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMathUtil, "sdk/VRChat/VRC/Dynamics/MathUtil.h");
}

std::string VRChatGeneratedVrcMemoryBuffer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMemoryBuffer, "sdk/VRChat/VRC/Dynamics/MemoryBuffer.h");
}

std::string VRChatGeneratedVrcParentChangeDetector() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcParentChangeDetector, "sdk/VRChat/VRC/Dynamics/ParentChangeDetector.h");
}

std::string VRChatGeneratedVrcParentVRCConstraintBinding() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcParentVRCConstraintBinding, "sdk/VRChat/VRC/Dynamics/ParentVRCConstraintBinding.h");
}

std::string VRChatGeneratedVrcPhysBoneGrabbedInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBoneGrabbedInfo, "sdk/VRChat/VRC/Dynamics/PhysBoneGrabbedInfo.h");
}

std::string VRChatGeneratedVrcPhysBoneGroup() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBoneGroup, "sdk/VRChat/VRC/Dynamics/PhysBoneGroup.h");
}

std::string VRChatGeneratedVrcPhysBoneManager() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBoneManager, "sdk/VRChat/VRC/Dynamics/PhysBoneManager.h");
}

std::string VRChatGeneratedVrcPhysBonePosedInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBonePosedInfo, "sdk/VRChat/VRC/Dynamics/PhysBonePosedInfo.h");
}

std::string VRChatGeneratedVrcPhysBoneReleasedInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBoneReleasedInfo, "sdk/VRChat/VRC/Dynamics/PhysBoneReleasedInfo.h");
}

std::string VRChatGeneratedVrcPhysBoneRoot() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBoneRoot, "sdk/VRChat/VRC/Dynamics/PhysBoneRoot.h");
}

std::string VRChatGeneratedVrcPhysBoneRootDefinition() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBoneRootDefinition, "sdk/VRChat/VRC/Dynamics/PhysBoneRootDefinition.h");
}

std::string VRChatGeneratedVrcPhysBoneUnPosedInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysBoneUnPosedInfo, "sdk/VRChat/VRC/Dynamics/PhysBoneUnPosedInfo.h");
}

std::string VRChatGeneratedVrcPositionVRCConstraintBinding() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPositionVRCConstraintBinding, "sdk/VRChat/VRC/Dynamics/PositionVRCConstraintBinding.h");
}

std::string VRChatGeneratedVrcReadTransformJob() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcReadTransformJob, "sdk/VRChat/VRC/Dynamics/ReadTransformJob.h");
}

std::string VRChatGeneratedVrcRootsBuffer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcRootsBuffer, "sdk/VRChat/VRC/Dynamics/RootsBuffer.h");
}

std::string VRChatGeneratedVrcRotationVRCConstraintBinding() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcRotationVRCConstraintBinding, "sdk/VRChat/VRC/Dynamics/RotationVRCConstraintBinding.h");
}

std::string VRChatGeneratedVrcScaleVRCConstraintBinding() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcScaleVRCConstraintBinding, "sdk/VRChat/VRC/Dynamics/ScaleVRCConstraintBinding.h");
}

std::string VRChatGeneratedVrcVRCConstraintBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintBase, "sdk/VRChat/VRC/Dynamics/VRCConstraintBase.h");
}

std::string VRChatGeneratedVrcVRCConstraintGroup() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintGroup, "sdk/VRChat/VRC/Dynamics/VRCConstraintGroup.h");
}

std::string VRChatGeneratedVrcVRCConstraintGrouper() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintGrouper, "sdk/VRChat/VRC/Dynamics/VRCConstraintGrouper.h");
}

std::string VRChatGeneratedVrcVRCConstraintJob() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintJob, "sdk/VRChat/VRC/Dynamics/VRCConstraintJob.h");
}

std::string VRChatGeneratedVrcVRCConstraintJobData() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintJobData, "sdk/VRChat/VRC/Dynamics/VRCConstraintJobData.h");
}

std::string VRChatGeneratedVrcVRCConstraintManager() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintManager, "sdk/VRChat/VRC/Dynamics/VRCConstraintManager.h");
}

std::string VRChatGeneratedVrcVRCConstraintOffsetBaker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintOffsetBaker, "sdk/VRChat/VRC/Dynamics/VRCConstraintOffsetBaker.h");
}

std::string VRChatGeneratedVrcVRCConstraintPlayerLoopStage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintPlayerLoopStage, "sdk/VRChat/VRC/Dynamics/VRCConstraintPlayerLoopStage.h");
}

std::string VRChatGeneratedVrcVRCConstraintPositionMode() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintPositionMode, "sdk/VRChat/VRC/Dynamics/VRCConstraintPositionMode.h");
}

std::string VRChatGeneratedVrcVRCConstraintRotationMode() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintRotationMode, "sdk/VRChat/VRC/Dynamics/VRCConstraintRotationMode.h");
}

std::string VRChatGeneratedVrcVRCConstraintScaleMode() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintScaleMode, "sdk/VRChat/VRC/Dynamics/VRCConstraintScaleMode.h");
}

std::string VRChatGeneratedVrcVRCConstraintSource() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintSource, "sdk/VRChat/VRC/Dynamics/VRCConstraintSource.h");
}

std::string VRChatGeneratedVrcVRCConstraintSourceKeyableList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintSourceKeyableList, "sdk/VRChat/VRC/Dynamics/VRCConstraintSourceKeyableList.h");
}

std::string VRChatGeneratedVrcVRCConstraintSynchronizeResult() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCConstraintSynchronizeResult, "sdk/VRChat/VRC/Dynamics/VRCConstraintSynchronizeResult.h");
}

std::string VRChatGeneratedVrcVRCDynamicsScheduler() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCDynamicsScheduler, "sdk/VRChat/VRC/Dynamics/VRCDynamicsScheduler.h");
}

std::string VRChatGeneratedVrcVRCPhysBoneBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPhysBoneBase, "sdk/VRChat/VRC/Dynamics/VRCPhysBoneBase.h");
}

std::string VRChatGeneratedVrcVRCPhysBoneColliderBase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPhysBoneColliderBase, "sdk/VRChat/VRC/Dynamics/VRCPhysBoneColliderBase.h");
}

std::string VRChatGeneratedVrcIProduct() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIProduct, "sdk/VRChat/VRC/Economy/IProduct.h");
}

std::string VRChatGeneratedVrcStore() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcStore, "sdk/VRChat/VRC/Economy/Store.h");
}

std::string VRChatGeneratedVrcUdonProduct() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUdonProduct, "sdk/VRChat/VRC/Economy/UdonProduct.h");
}

std::string VRChatGeneratedVrcUdonProductsCategory() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUdonProductsCategory, "sdk/VRChat/VRC/Economy/UdonProductsCategory.h");
}

std::string VRChatGeneratedVrcDroneSkinMapCore() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDroneSkinMapCore, "sdk/VRChat/VRC/InventoryEffects/DroneSkinMapCore.h");
}

std::string VRChatGeneratedVrcInventoryContentType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInventoryContentType, "sdk/VRChat/VRC/InventoryEffects/InventoryContentType.h");
}

std::string VRChatGeneratedVrcInventoryEffectAssetReference() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInventoryEffectAssetReference, "sdk/VRChat/VRC/InventoryEffects/InventoryEffectAssetReference.h");
}

std::string VRChatGeneratedVrcInventoryEffectDescription() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInventoryEffectDescription, "sdk/VRChat/VRC/InventoryEffects/InventoryEffectDescription.h");
}

std::string VRChatGeneratedVrcInventoryEffectDescriptionKeys() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInventoryEffectDescriptionKeys, "sdk/VRChat/VRC/InventoryEffects/InventoryEffectDescriptionKeys.h");
}

std::string VRChatGeneratedVrcLocalPositionTracker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLocalPositionTracker, "sdk/VRChat/VRC/InventoryEffects/LocalPositionTracker.h");
}

std::string VRChatGeneratedVrcWarpEffect() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcWarpEffect, "sdk/VRChat/VRC/InventoryEffects/WarpEffect.h");
}

std::string VRChatGeneratedVrcWarpEffectMap() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcWarpEffectMap, "sdk/VRChat/VRC/InventoryEffects/WarpEffectMap.h");
}

std::string VRChatGeneratedVrcWarpEffectParams() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcWarpEffectParams, "sdk/VRChat/VRC/InventoryEffects/WarpEffectParams.h");
}

std::string VRChatGeneratedVrcLocalizableString() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLocalizableString, "sdk/VRChat/VRC/Localization/LocalizableString.h");
}

std::string VRChatGeneratedVrcLocalizableStringFormatter() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLocalizableStringFormatter, "sdk/VRChat/VRC/Localization/LocalizableStringFormatter.h");
}

std::string VRChatGeneratedVrcLocalizationAsset() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLocalizationAsset, "sdk/VRChat/VRC/Localization/LocalizationAsset.h");
}

std::string VRChatGeneratedVrcLocalizationDatabase() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLocalizationDatabase, "sdk/VRChat/VRC/Localization/LocalizationDatabase.h");
}

std::string VRChatGeneratedVrcVRCAvatarDescriptor() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCAvatarDescriptor, "sdk/VRChat/VRC/SDK3/Avatars/Components/VRCAvatarDescriptor.h");
}

std::string VRChatGeneratedVrcVRCHeadChop() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCHeadChop, "sdk/VRChat/VRC/SDK3/Avatars/Components/VRCHeadChop.h");
}

std::string VRChatGeneratedVrcVRCImpostorEnvironment() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCImpostorEnvironment, "sdk/VRChat/VRC/SDK3/Avatars/Components/VRCImpostorEnvironment.h");
}

std::string VRChatGeneratedVrcVRCImpostorSettings() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCImpostorSettings, "sdk/VRChat/VRC/SDK3/Avatars/Components/VRCImpostorSettings.h");
}

std::string VRChatGeneratedVrcAbstractUdonBehaviour() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAbstractUdonBehaviour, "sdk/VRChat/VRC/SDK3/Components/AbstractUdonBehaviour.h");
}

std::string VRChatGeneratedVrcMirrorClearFlags() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMirrorClearFlags, "sdk/VRChat/VRC/SDK3/Components/MirrorClearFlags.h");
}

std::string VRChatGeneratedVrcMultipleDisplayUtilities() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMultipleDisplayUtilities, "sdk/VRChat/VRC/SDK3/Components/MultipleDisplayUtilities.h");
}

std::string VRChatGeneratedVrcSetPropertyUtility() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcSetPropertyUtility, "sdk/VRChat/VRC/SDK3/Components/SetPropertyUtility.h");
}

std::string VRChatGeneratedVrcVideoError() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVideoError, "sdk/VRChat/VRC/SDK3/Components/Video/VideoError.h");
}

std::string VRChatGeneratedVrcVRCDepthkitMetadata() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCDepthkitMetadata, "sdk/VRChat/VRC/SDK3/Components/Video/VRCDepthkit/VRCDepthkitMetadata.h");
}

std::string VRChatGeneratedVrcVRCDepthkitVideo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCDepthkitVideo, "sdk/VRChat/VRC/SDK3/Components/Video/VRCDepthkit/VRCDepthkitVideo.h");
}

std::string VRChatGeneratedVrcVRCAvatarPedestal() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCAvatarPedestal, "sdk/VRChat/VRC/SDK3/Components/VRCAvatarPedestal.h");
}

std::string VRChatGeneratedVrcVRCEnablePersistence() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCEnablePersistence, "sdk/VRChat/VRC/SDK3/Components/VRCEnablePersistence.h");
}

std::string VRChatGeneratedVrcVRCInputFieldKeyboardOverride() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCInputFieldKeyboardOverride, "sdk/VRChat/VRC/SDK3/Components/VRCInputFieldKeyboardOverride.h");
}

std::string VRChatGeneratedVrcVRCInteractable() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCInteractable, "sdk/VRChat/VRC/SDK3/Components/VRCInteractable.h");
}

std::string VRChatGeneratedVrcVRCMirrorReflection() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCMirrorReflection, "sdk/VRChat/VRC/SDK3/Components/VRCMirrorReflection.h");
}

std::string VRChatGeneratedVrcVRCObjectPool() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCObjectPool, "sdk/VRChat/VRC/SDK3/Components/VRCObjectPool.h");
}

std::string VRChatGeneratedVrcVRCObjectSync() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCObjectSync, "sdk/VRChat/VRC/SDK3/Components/VRCObjectSync.h");
}

std::string VRChatGeneratedVrcVRCOpenMenu() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCOpenMenu, "sdk/VRChat/VRC/SDK3/Components/VRCOpenMenu.h");
}

std::string VRChatGeneratedVrcVRCPlayerObject() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPlayerObject, "sdk/VRChat/VRC/SDK3/Components/VRCPlayerObject.h");
}

std::string VRChatGeneratedVrcVRCPortalMarker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPortalMarker, "sdk/VRChat/VRC/SDK3/Components/VRCPortalMarker.h");
}

std::string VRChatGeneratedVrcVRCSceneDescriptor() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCSceneDescriptor, "sdk/VRChat/VRC/SDK3/Components/VRCSceneDescriptor.h");
}

std::string VRChatGeneratedVrcVRCSpatialAudioSource() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCSpatialAudioSource, "sdk/VRChat/VRC/SDK3/Components/VRCSpatialAudioSource.h");
}

std::string VRChatGeneratedVrcVRCStation() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCStation, "sdk/VRChat/VRC/SDK3/Components/VRCStation.h");
}

std::string VRChatGeneratedVrcVRCTMPDropdownExtension() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCTMPDropdownExtension, "sdk/VRChat/VRC/SDK3/Components/VRCTMPDropdownExtension.h");
}

std::string VRChatGeneratedVrcVRCUiShape() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCUiShape, "sdk/VRChat/VRC/SDK3/Components/VRCUiShape.h");
}

std::string VRChatGeneratedVrcVRCUrlInputField() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCUrlInputField, "sdk/VRChat/VRC/SDK3/Components/VRCUrlInputField.h");
}

std::string VRChatGeneratedVrcVRCVisualDamage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCVisualDamage, "sdk/VRChat/VRC/SDK3/Components/VRCVisualDamage.h");
}

std::string VRChatGeneratedVrcControllerColliderPlayerHit() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcControllerColliderPlayerHit, "sdk/VRChat/VRC/SDK3/ControllerColliderPlayerHit.h");
}

std::string VRChatGeneratedVrcDataDictionary() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDataDictionary, "sdk/VRChat/VRC/SDK3/Data/DataDictionary.h");
}

std::string VRChatGeneratedVrcDataError() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDataError, "sdk/VRChat/VRC/SDK3/Data/DataError.h");
}

std::string VRChatGeneratedVrcDataList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDataList, "sdk/VRChat/VRC/SDK3/Data/DataList.h");
}

std::string VRChatGeneratedVrcDataToken() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDataToken, "sdk/VRChat/VRC/SDK3/Data/DataToken.h");
}

std::string VRChatGeneratedVrcJsonDictionary() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcJsonDictionary, "sdk/VRChat/VRC/SDK3/Data/JsonDictionary.h");
}

std::string VRChatGeneratedVrcJsonExportType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcJsonExportType, "sdk/VRChat/VRC/SDK3/Data/JsonExportType.h");
}

std::string VRChatGeneratedVrcJsonList() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcJsonList, "sdk/VRChat/VRC/SDK3/Data/JsonList.h");
}

std::string VRChatGeneratedVrcJsonType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcJsonType, "sdk/VRChat/VRC/SDK3/Data/JsonType.h");
}

std::string VRChatGeneratedVrcParseState() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcParseState, "sdk/VRChat/VRC/SDK3/Data/ParseState.h");
}

std::string VRChatGeneratedVrcTokenType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTokenType, "sdk/VRChat/VRC/SDK3/Data/TokenType.h");
}

std::string VRChatGeneratedVrcVRCJson() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCJson, "sdk/VRChat/VRC/SDK3/Data/VRCJson.h");
}

std::string VRChatGeneratedVrcVRCContactReceiver() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCContactReceiver, "sdk/VRChat/VRC/SDK3/Dynamics/Contact/Components/VRCContactReceiver.h");
}

std::string VRChatGeneratedVrcVRCContactSender() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCContactSender, "sdk/VRChat/VRC/SDK3/Dynamics/Contact/Components/VRCContactSender.h");
}

std::string VRChatGeneratedVrcVRCPhysBone() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPhysBone, "sdk/VRChat/VRC/SDK3/Dynamics/PhysBone/Components/VRCPhysBone.h");
}

std::string VRChatGeneratedVrcVRCPhysBoneCollider() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPhysBoneCollider, "sdk/VRChat/VRC/SDK3/Dynamics/PhysBone/Components/VRCPhysBoneCollider.h");
}

std::string VRChatGeneratedVrcVRCPhysBoneRoot() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPhysBoneRoot, "sdk/VRChat/VRC/SDK3/Dynamics/PhysBone/Components/VRCPhysBoneRoot.h");
}

std::string VRChatGeneratedVrcImageDownloader() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcImageDownloader, "sdk/VRChat/VRC/SDK3/Image/ImageDownloader.h");
}

std::string VRChatGeneratedVrcImageLoadError() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcImageLoadError, "sdk/VRChat/VRC/SDK3/Image/ImageLoadError.h");
}

std::string VRChatGeneratedVrcIVRCImageDownload() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRCImageDownload, "sdk/VRChat/VRC/SDK3/Image/IVRCImageDownload.h");
}

std::string VRChatGeneratedVrcTextureInfo() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTextureInfo, "sdk/VRChat/VRC/SDK3/Image/TextureInfo.h");
}

std::string VRChatGeneratedVrcVRCImageDownloader() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCImageDownloader, "sdk/VRChat/VRC/SDK3/Image/VRCImageDownloader.h");
}

std::string VRChatGeneratedVrcVRCImageDownloadError() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCImageDownloadError, "sdk/VRChat/VRC/SDK3/Image/VRCImageDownloadError.h");
}

std::string VRChatGeneratedVrcVRCImageDownloadState() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCImageDownloadState, "sdk/VRChat/VRC/SDK3/Image/VRCImageDownloadState.h");
}

std::string VRChatGeneratedVrcStats() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcStats, "sdk/VRChat/VRC/SDK3/Network/Stats.h");
}

std::string VRChatGeneratedVrcVRCNetworkBehaviour() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCNetworkBehaviour, "sdk/VRChat/VRC/SDK3/Network/VRCNetworkBehaviour.h");
}

std::string VRChatGeneratedVrcVRCUdonSyncType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCUdonSyncType, "sdk/VRChat/VRC/SDK3/Network/VRCUdonSyncType.h");
}

std::string VRChatGeneratedVrcVRCUdonSyncTypeConverter() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCUdonSyncTypeConverter, "sdk/VRChat/VRC/SDK3/Network/VRCUdonSyncTypeConverter.h");
}

std::string VRChatGeneratedVrcPlayerData() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPlayerData, "sdk/VRChat/VRC/SDK3/Persistence/PlayerData.h");
}

std::string VRChatGeneratedVrcScreenUpdateData() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcScreenUpdateData, "sdk/VRChat/VRC/SDK3/Platform/ScreenUpdateData.h");
}

std::string VRChatGeneratedVrcScreenUpdateType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcScreenUpdateType, "sdk/VRChat/VRC/SDK3/Platform/ScreenUpdateType.h");
}

std::string VRChatGeneratedVrcCustomAttribute() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCustomAttribute, "sdk/VRChat/VRC/SDK3/Props/Components/CustomAttribute.h");
}

std::string VRChatGeneratedVrcCustomAttributeType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCustomAttributeType, "sdk/VRChat/VRC/SDK3/Props/Components/CustomAttributeType.h");
}

std::string VRChatGeneratedVrcVRCPropDescriptor() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPropDescriptor, "sdk/VRChat/VRC/SDK3/Props/Components/VRCPropDescriptor.h");
}

std::string VRChatGeneratedVrcSpawnType() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcSpawnType, "sdk/VRChat/VRC/SDK3/Props/SpawnType.h");
}

std::string VRChatGeneratedVrcVRCPropApi() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPropApi, "sdk/VRChat/VRC/SDK3/Props/VRCPropApi.h");
}

std::string VRChatGeneratedVrcVRCPropUtilities() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCPropUtilities, "sdk/VRChat/VRC/SDK3/Props/VRCPropUtilities.h");
}

std::string VRChatGeneratedVrcWorldSpawnPlacement() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcWorldSpawnPlacement, "sdk/VRChat/VRC/SDK3/Props/WorldSpawnPlacement.h");
}

std::string VRChatGeneratedVrcVRCAsyncGPUReadbackRequest() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCAsyncGPUReadbackRequest, "sdk/VRChat/VRC/SDK3/Rendering/VRCAsyncGPUReadbackRequest.h");
}

std::string VRChatGeneratedVrcVRCCameraMode() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCCameraMode, "sdk/VRChat/VRC/SDK3/Rendering/VRCCameraMode.h");
}

std::string VRChatGeneratedVrcVRCCameraSettings() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCCameraSettings, "sdk/VRChat/VRC/SDK3/Rendering/VRCCameraSettings.h");
}

std::string VRChatGeneratedVrcVRCQualitySettings() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCQualitySettings, "sdk/VRChat/VRC/SDK3/Rendering/VRCQualitySettings.h");
}

std::string VRChatGeneratedVrcIVRCStringDownload() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRCStringDownload, "sdk/VRChat/VRC/SDK3/StringLoading/IVRCStringDownload.h");
}

std::string VRChatGeneratedVrcMaxBufferDownloadHandler() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMaxBufferDownloadHandler, "sdk/VRChat/VRC/SDK3/StringLoading/MaxBufferDownloadHandler.h");
}

std::string VRChatGeneratedVrcVRCStringDownload() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCStringDownload, "sdk/VRChat/VRC/SDK3/StringLoading/VRCStringDownload.h");
}

std::string VRChatGeneratedVrcVRCStringDownloader() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCStringDownloader, "sdk/VRChat/VRC/SDK3/StringLoading/VRCStringDownloader.h");
}

std::string VRChatGeneratedVrcIUdonSignatureHolder() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIUdonSignatureHolder, "sdk/VRChat/VRC/Udon/Security/IUdonSignatureHolder.h");
}

std::string VRChatGeneratedVrcIUdonSignatureVerifier() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIUdonSignatureVerifier, "sdk/VRChat/VRC/Udon/Security/IUdonSignatureVerifier.h");
}

std::string VRChatGeneratedVrcNetworkCallableAttribute() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkCallableAttribute, "sdk/VRChat/VRC/SDK3/UdonNetworkCalling/NetworkCallableAttribute.h");
}

std::string VRChatGeneratedVrcNetworkCalling() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkCalling, "sdk/VRChat/VRC/SDK3/UdonNetworkCalling/NetworkCalling.h");
}

std::string VRChatGeneratedVrcNetworkCallingEntrypointMetadata() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkCallingEntrypointMetadata, "sdk/VRChat/VRC/SDK3/UdonNetworkCalling/NetworkCallingEntrypointMetadata.h");
}

std::string VRChatGeneratedVrcNetworkCallingParameterMetadata() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkCallingParameterMetadata, "sdk/VRChat/VRC/SDK3/UdonNetworkCalling/NetworkCallingParameterMetadata.h");
}

std::string VRChatGeneratedVrcVRCAVProVideoPlayer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCAVProVideoPlayer, "sdk/VRChat/VRC/SDK3/Video/Components/AVPro/VRCAVProVideoPlayer.h");
}

std::string VRChatGeneratedVrcVRCAVProVideoScreen() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCAVProVideoScreen, "sdk/VRChat/VRC/SDK3/Video/Components/AVPro/VRCAVProVideoScreen.h");
}

std::string VRChatGeneratedVrcVRCAVProVideoSpeaker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCAVProVideoSpeaker, "sdk/VRChat/VRC/SDK3/Video/Components/AVPro/VRCAVProVideoSpeaker.h");
}

std::string VRChatGeneratedVrcBaseVRCVideoPlayer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcBaseVRCVideoPlayer, "sdk/VRChat/VRC/SDK3/Video/Components/Base/BaseVRCVideoPlayer.h");
}

std::string VRChatGeneratedVrcVRCUnityVideoPlayer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCUnityVideoPlayer, "sdk/VRChat/VRC/SDK3/Video/Components/VRCUnityVideoPlayer.h");
}

std::string VRChatGeneratedVrcIAVProVideoPlayerInternal() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIAVProVideoPlayerInternal, "sdk/VRChat/VRC/SDK3/Video/Interfaces/AVPro/IAVProVideoPlayerInternal.h");
}

std::string VRChatGeneratedVrcIVRCVideoPlayer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRCVideoPlayer, "sdk/VRChat/VRC/SDK3/Video/Interfaces/IVRCVideoPlayer.h");
}

std::string VRChatGeneratedVrcVRCTestMarker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCTestMarker, "sdk/VRChat/VRC/SDK3/VRCTestMarker.h");
}

std::string VRChatGeneratedVrcCurveAttribute() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcCurveAttribute, "sdk/VRChat/VRC/SDKBase/Editor/Attributes/CurveAttribute.h");
}

std::string VRChatGeneratedVrcHelpBoxAttribute() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcHelpBoxAttribute, "sdk/VRChat/VRC/SDKBase/Editor/Attributes/HelpBoxAttribute.h");
}

std::string VRChatGeneratedVrcIAnimParameterAccess() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIAnimParameterAccess, "sdk/VRChat/VRC/SDKBase/IAnimParameterAccess.h");
}

std::string VRChatGeneratedVrcINetworkIDContainer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcINetworkIDContainer, "sdk/VRChat/VRC/SDKBase/INetworkIDContainer.h");
}

std::string VRChatGeneratedVrcInputManager() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInputManager, "sdk/VRChat/VRC/SDKBase/InputManager.h");
}

std::string VRChatGeneratedVrcIValidChecker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIValidChecker, "sdk/VRChat/VRC/SDKBase/IValidChecker.h");
}

std::string VRChatGeneratedVrcIVRC_Destructible() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRC_Destructible, "sdk/VRChat/VRC/SDKBase/IVRC_Destructible.h");
}

std::string VRChatGeneratedVrcNetworkIDAssignment() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkIDAssignment, "sdk/VRChat/VRC/SDKBase/Network/NetworkIDAssignment.h");
}

std::string VRChatGeneratedVrcNetworkIDPair() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNetworkIDPair, "sdk/VRChat/VRC/SDKBase/Network/NetworkIDPair.h");
}

std::string VRChatGeneratedVrcVRCOrientation() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCOrientation, "sdk/VRChat/VRC/SDKBase/Platform/VRCOrientation.h");
}

std::string VRChatGeneratedVrcIVRCInteractable() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIVRCInteractable, "sdk/VRChat/VRC/SDKBase/Source/IVRCInteractable.h");
}

std::string VRChatGeneratedVrcUtilities() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUtilities, "sdk/VRChat/VRC/SDKBase/Utilities.h");
}

std::string VRChatGeneratedVrcVersionHelper() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVersionHelper, "sdk/VRChat/VRC/SDKBase/VersionHelper.h");
}

std::string VRChatGeneratedVrcAnimatorLayerControl() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimatorLayerControl, "sdk/VRChat/VRC/SDKBase/VRC_AnimatorLayerControl.h");
}

std::string VRChatGeneratedVrcAnimatorLocomotionControl() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimatorLocomotionControl, "sdk/VRChat/VRC/SDKBase/VRC_AnimatorLocomotionControl.h");
}

std::string VRChatGeneratedVrcAnimatorPlayAudio() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimatorPlayAudio, "sdk/VRChat/VRC/SDKBase/VRC_AnimatorPlayAudio.h");
}

std::string VRChatGeneratedVrcAnimatorTemporaryPoseSpace() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimatorTemporaryPoseSpace, "sdk/VRChat/VRC/SDKBase/VRC_AnimatorTemporaryPoseSpace.h");
}

std::string VRChatGeneratedVrcAnimatorTrackingControl() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAnimatorTrackingControl, "sdk/VRChat/VRC/SDKBase/VRC_AnimatorTrackingControl.h");
}

std::string VRChatGeneratedVrcAvatarDescriptor() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAvatarDescriptor, "sdk/VRChat/VRC/SDKBase/VRC_AvatarDescriptor.h");
}

std::string VRChatGeneratedVrcAvatarParameterDriver() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcAvatarParameterDriver, "sdk/VRChat/VRC/SDKBase/VRC_AvatarParameterDriver.h");
}

std::string VRChatGeneratedVrcDataStorage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDataStorage, "sdk/VRChat/VRC/SDKBase/VRC_DataStorage.h");
}

std::string VRChatGeneratedVrcDestructibleStandard() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcDestructibleStandard, "sdk/VRChat/VRC/SDKBase/VRC_DestructibleStandard.h");
}

std::string VRChatGeneratedVrcEventDispatcher() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcEventDispatcher, "sdk/VRChat/VRC/SDKBase/VRC_EventDispatcher.h");
}

std::string VRChatGeneratedVrcEventDispatcherLocal() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcEventDispatcherLocal, "sdk/VRChat/VRC/SDKBase/VRC_EventDispatcherLocal.h");
}

std::string VRChatGeneratedVrcEventHandler() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcEventHandler, "sdk/VRChat/VRC/SDKBase/VRC_EventHandler.h");
}

std::string VRChatGeneratedVrcGunStats() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcGunStats, "sdk/VRChat/VRC/SDKBase/VRC_GunStats.h");
}

std::string VRChatGeneratedVrcIKFollower() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcIKFollower, "sdk/VRChat/VRC/SDKBase/VRC_IKFollower.h");
}

std::string VRChatGeneratedVrcInteractable() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcInteractable, "sdk/VRChat/VRC/SDKBase/VRC_Interactable.h");
}

std::string VRChatGeneratedVrcKeyEvents() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcKeyEvents, "sdk/VRChat/VRC/SDKBase/VRC_KeyEvents.h");
}

std::string VRChatGeneratedVrcLabel() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcLabel, "sdk/VRChat/VRC/SDKBase/VRC_Label.h");
}

std::string VRChatGeneratedVrcMetadataListener() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMetadataListener, "sdk/VRChat/VRC/SDKBase/VRC_MetadataListener.h");
}

std::string VRChatGeneratedVrcMidiNoteIn() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMidiNoteIn, "sdk/VRChat/VRC/SDKBase/VRC_MidiNoteIn.h");
}

std::string VRChatGeneratedVrcMirrorReflection() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcMirrorReflection, "sdk/VRChat/VRC/SDKBase/VRC_MirrorReflection.h");
}

std::string VRChatGeneratedVrcNpcApi() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNpcApi, "sdk/VRChat/VRC/SDKBase/VRC_NpcApi.h");
}

std::string VRChatGeneratedVrcNPCSpawn() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcNPCSpawn, "sdk/VRChat/VRC/SDKBase/VRC_NPCSpawn.h");
}

std::string VRChatGeneratedVrcObjectApi() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcObjectApi, "sdk/VRChat/VRC/SDKBase/VRC_ObjectApi.h");
}

std::string VRChatGeneratedVrcObjectSpawn() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcObjectSpawn, "sdk/VRChat/VRC/SDKBase/VRC_ObjectSpawn.h");
}

std::string VRChatGeneratedVrcOscButtonIn() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcOscButtonIn, "sdk/VRChat/VRC/SDKBase/VRC_OscButtonIn.h");
}

std::string VRChatGeneratedVrcPanorama() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPanorama, "sdk/VRChat/VRC/SDKBase/VRC_Panorama.h");
}

std::string VRChatGeneratedVrcPhysicsRoot() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPhysicsRoot, "sdk/VRChat/VRC/SDKBase/VRC_PhysicsRoot.h");
}

std::string VRChatGeneratedVrcPlayableLayerControl() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPlayableLayerControl, "sdk/VRChat/VRC/SDKBase/VRC_PlayableLayerControl.h");
}

std::string VRChatGeneratedVrcPortalMarker() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPortalMarker, "sdk/VRChat/VRC/SDKBase/VRC_PortalMarker.h");
}

std::string VRChatGeneratedVrcPropApi() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPropApi, "sdk/VRChat/VRC/SDKBase/VRC_PropApi.h");
}

std::string VRChatGeneratedVrcPropController() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPropController, "sdk/VRChat/VRC/SDKBase/VRC_PropController.h");
}

std::string VRChatGeneratedVrcPropDescriptor() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcPropDescriptor, "sdk/VRChat/VRC/SDKBase/VRC_PropDescriptor.h");
}

std::string VRChatGeneratedVrcSlideShow() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcSlideShow, "sdk/VRChat/VRC/SDKBase/VRC_SlideShow.h");
}

std::string VRChatGeneratedVrcSpecialLayer() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcSpecialLayer, "sdk/VRChat/VRC/SDKBase/VRC_SpecialLayer.h");
}

std::string VRChatGeneratedVrcTimedEvents() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTimedEvents, "sdk/VRChat/VRC/SDKBase/VRC_TimedEvents.h");
}

std::string VRChatGeneratedVrcTrigger() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTrigger, "sdk/VRChat/VRC/SDKBase/VRC_Trigger.h");
}

std::string VRChatGeneratedVrcTriggerColliderEventTrigger() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcTriggerColliderEventTrigger, "sdk/VRChat/VRC/SDKBase/VRC_TriggerColliderEventTrigger.h");
}

std::string VRChatGeneratedVrcUiShape() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUiShape, "sdk/VRChat/VRC/SDKBase/VRC_UiShape.h");
}

std::string VRChatGeneratedVrcUseEvents() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcUseEvents, "sdk/VRChat/VRC/SDKBase/VRC_UseEvents.h");
}

std::string VRChatGeneratedVrcVisualDamage() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVisualDamage, "sdk/VRChat/VRC/SDKBase/VRC_VisualDamage.h");
}

std::string VRChatGeneratedVrcWater() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcWater, "sdk/VRChat/VRC/SDKBase/VRC_Water.h");
}

std::string VRChatGeneratedVrcWebPanel() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcWebPanel, "sdk/VRChat/VRC/SDKBase/VRC_WebPanel.h");
}

std::string VRChatGeneratedVrcVRCCustomAction() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCCustomAction, "sdk/VRChat/VRC/SDKBase/VRCCustomAction.h");
}

std::string VRChatGeneratedVrcVRCDroneApi() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCDroneApi, "sdk/VRChat/VRC/SDKBase/VRCDroneApi.h");
}

std::string VRChatGeneratedVrcVRCGraphics() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCGraphics, "sdk/VRChat/VRC/SDKBase/VRCGraphics.h");
}

std::string VRChatGeneratedVrcVRCInputMethod() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCInputMethod, "sdk/VRChat/VRC/SDKBase/VRCInputMethod.h");
}

std::string VRChatGeneratedVrcVRCInputSetting() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCInputSetting, "sdk/VRChat/VRC/SDKBase/VRCInputSetting.h");
}

std::string VRChatGeneratedVrcVRCRenderTexture() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCRenderTexture, "sdk/VRChat/VRC/SDKBase/VRCRenderTexture.h");
}

std::string VRChatGeneratedVrcVRCShader() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCShader, "sdk/VRChat/VRC/SDKBase/VRCShader.h");
}

std::string VRChatGeneratedVrcVRCTriggerRelay() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCTriggerRelay, "sdk/VRChat/VRC/SDKBase/VRCTriggerRelay.h");
}

std::string VRChatGeneratedVrcVRCUrl() {
    return VrcGenerated::EmitType(VrcGenerated::kVrcVRCUrl, "sdk/VRChat/VRC/SDKBase/VRCUrl.h");
}

} // namespace