// GENERATED by tools/regen_vrchat_table.ps1. Do not edit by hand.
// Every managed enum in the capture. IsManagedEnum consults this so a new
// enum does not need a hand edit, and so a member of an enum type is not
// emitted as void* and read as a pointer where the value is an integer.
#define URK_VRCHAT_GENERATED_ENUMS 1

namespace VrcGenerated {

inline const char *const kVrcGeneratedEnumNames[] = {
    "VRC.Core.AnalyticsEventOptions",
    "VRC.Core.ApiOnlineMode",
    "VRC.Core.ApiServerEnvironment",
    "VRC.Core.FavoritePrivacy",
    "VRC.Core.FavoriteType",
    "VRC.Core.InstanceAccessType",
    "VRC.Core.LicenseType",
    "VRC.Core.ListingType",
    "VRC.Core.LoggingMode",
    "VRC.Core.NetworkRegion",
    "VRC.Core.Networking.Pose.PoseContents",
    "VRC.Core.Networking.VRCNetworkBehaviourTypeId",
    "VRC.Core.ProductType",
    "VRC.Core.Services.APIEventSource",
    "VRC.Core.TimeInterval",
    "VRC.Core.VTP_PacketID",
    "VRC.Dynamics.DynamicsUsage",
    "VRC.Dynamics.DynamicsUsageFlags",
    "VRC.Dynamics.VRCConstraintPlayerLoopStage",
    "VRC.Dynamics.VRCConstraintPositionMode",
    "VRC.Dynamics.VRCConstraintRotationMode",
    "VRC.Dynamics.VRCConstraintScaleMode",
    "VRC.Dynamics.VRCConstraintSynchronizeResult",
    "VRC.InventoryEffects.InventoryContentType",
    "VRC.SDK3.Components.MirrorClearFlags",
    "VRC.SDK3.Components.Video.VideoError",
    "VRC.SDK3.Data.DataError",
    "VRC.SDK3.Data.JsonExportType",
    "VRC.SDK3.Data.JsonType",
    "VRC.SDK3.Data.ParseState",
    "VRC.SDK3.Data.TokenType",
    "VRC.SDK3.Image.ImageLoadError",
    "VRC.SDK3.Image.VRCImageDownloadError",
    "VRC.SDK3.Image.VRCImageDownloadState",
    "VRC.SDK3.Network.VRCUdonSyncType",
    "VRC.SDK3.Platform.ScreenUpdateType",
    "VRC.SDK3.Props.Components.CustomAttributeType",
    "VRC.SDK3.Props.SpawnType",
    "VRC.SDK3.Props.WorldSpawnPlacement",
    "VRC.SDK3.Rendering.VRCCameraMode",
    "VRC.SDKBase.Platform.VRCOrientation",
    "VRC.SDKBase.VRCInputMethod",
    "VRC.SDKBase.VRCInputSetting",
    "VRC.SDKBase.VRCLayers",
    nullptr,
};

inline const char *const *VrcGeneratedEnumNames() {
    return kVrcGeneratedEnumNames;
}

} // namespace VrcGenerated