<#
.SYNOPSIS
    Regenerates the VRChat type table, factories, and generator write list.

.DESCRIPTION
    Runs the two halves of the capture pipeline and splices the results into the
    files the generator includes:

      tools/extract_sdk_capture.ps1   decompiled C# -> capture json
      urk-vrchat-table-gen            capture json -> table entries

    The hand-written entries in vrchat_generated_table.inl are excluded and left
    alone: they carry alt_name resilience that regenerated data cannot reproduce.
    Everything between the generated markers is replaced wholesale, so this is
    safe to re-run after a VRChat update.
#>
param(
    [string]$Repo        = (Split-Path -Parent $PSScriptRoot),
    [string]$Decompile  = 'C:\Users\Biscuit\Desktop\VRCDecompile\VRChat',
    [string]$Generator  = "$Repo\out\build\msvc-release\urk-vrchat-table-gen.exe",
    [switch]$SkipExtract
)

$ErrorActionPreference = 'Stop'

$tableDir = "$Repo\src\sdk\templates\VRChat"
$table    = "$tableDir\vrchat_generated_table.inl"
$enumsOut = "$tableDir\vrchat_generated_enums.inl"
$typesOut = "$tableDir\vrchat_generated_types.inl"
$factOut  = "$tableDir\vrchat_generated_factories.inl"
$common   = "$Repo\src\sdk\mod_project_generator_common.cpp"
$capture  = "$PSScriptRoot\vrchat_slice.decompile.json"

if (-not $SkipExtract) {
    Write-Output 'extracting capture from decompile...'
    & powershell -NoProfile -ExecutionPolicy Bypass -File "$PSScriptRoot\extract_sdk_capture.ps1" `
        -Decompile $Decompile -Out $capture | Out-Null
}

if (-not (Test-Path $Generator)) { throw "generator not built: $Generator" }

# The hand-written specs are read out of the table rather than listed here, so
# they can never drift from what is actually there. They are excluded because
# regenerating them would drop their alt_name resilience, which is the whole
# point of the resilience layer. The managed identity is the 4th and 5th string
# of a TypeSpec: cpp_name, cpp_namespace, image, managed_namespace, class.
$tableText = Get-Content -LiteralPath $table -Raw
$specRx = [regex]'(?s)inline const TypeSpec k\w+ = \{.*?", "[^"]+\.dll", "([^"]+)", "([^"]+)",'
$handWritten = @($specRx.Matches($tableText) |
    ForEach-Object { $_.Groups[1].Value + '.' + $_.Groups[2].Value })
if ($handWritten.Count -lt 1) { throw 'no hand-written TypeSpec entries found in the table' }

$excludeFile = Join-Path $env:TEMP 'urk-vrchat-exclude.txt'
Set-Content -LiteralPath $excludeFile -Value $handWritten -Encoding ascii
Write-Output "excluding $($handWritten.Count) hand-written types"

# Header paths already claimed by any other template. The generator's ledger
# rejects a duplicate path, so a generated type that lands on one of these has to
# yield to the hand-written template. Read from the write list itself so a new
# template is picked up without touching this script.
$commonText = Get-Content -LiteralPath $common -Raw
$commonText = [regex]::Replace($commonText,
    '(?s)// >>> VRCHAT_GENERATED_WRITES >>>.*?// <<< VRCHAT_GENERATED_WRITES <<<', '')
$pathRx = [regex]'\{("(?:[^"\\]|\\.)*\.h")\s*,\s*OutputFilePolicy'
$taken = @($pathRx.Matches($commonText) | ForEach-Object { $_.Groups[1].Value.Trim('"') } |
    Sort-Object -Unique)
$reserveFile = Join-Path $env:TEMP 'urk-vrchat-reserved.txt'
Set-Content -LiteralPath $reserveFile -Value $taken -Encoding ascii
Write-Output "reserving $($taken.Count) claimed header paths"

# Stderr is the fidelity report, not a failure. It goes to a file because
# ErrorActionPreference = Stop would otherwise turn native stderr into a
# terminating error and abort before the sections can be split.
$errFile = Join-Path $env:TEMP 'urk-vrchat-table-gen.err'
$outFile = Join-Path $env:TEMP 'urk-vrchat-table-gen.out'
# A native command that writes to stderr raises a terminating error under Stop,
# even with a redirect, so this one call runs with the preference relaxed.
$ErrorActionPreference = 'Continue'
& $Generator $capture --factories --writes --exclude-file $excludeFile --reserve-file $reserveFile 1> $outFile 2> $errFile
$exit = $LASTEXITCODE
$ErrorActionPreference = 'Stop'
if ($exit -ne 0) {
    Get-Content $errFile | ForEach-Object { "  $_" }
    throw "generator exited $exit"
}

$err = @(Get-Content $errFile)
$out = @(Get-Content $outFile)

$joined = ($out -join "`n")
$sections = @{}
foreach ($name in @('enums','types','factories','writes')) {
    $m = [regex]::Match($joined, "(?s)//=== SECTION: $name ===\r?\n(.*?)(?=//=== SECTION: |\z)")
    if (-not $m.Success) { throw "section '$name' missing from generator output" }
    $sections[$name] = $m.Groups[1].Value.TrimEnd()
}

$count = ([regex]::Matches($sections['types'], '(?m)^inline const VrcGenerated::TypeSpec ')).Count
Write-Output "generated $count types"

# --- 1. the enum name table, included ahead of the emitter --------------------

$enumBanner = @(
    '// GENERATED by tools/regen_vrchat_table.ps1. Do not edit by hand.',
    '// Every managed enum in the capture. IsManagedEnum consults this so a new',
    '// enum does not need a hand edit, and so a member of an enum type is not',
    '// emitted as void* and read as a pointer where the value is an integer.',
    '#define URK_VRCHAT_GENERATED_ENUMS 1',
    ''
)
Set-Content -LiteralPath $enumsOut -Value (($enumBanner + $sections['enums']) -join "`n") -NoNewline

# --- 2. the specs, included from inside namespace VrcGenerated ----------------

$banner = @(
    '// GENERATED by tools/regen_vrchat_table.ps1. Do not edit by hand.',
    "// Types: $count. Source: $capture",
    ''
)
Set-Content -LiteralPath $typesOut -Value (($banner + $sections['types']) -join "`n") -NoNewline

# --- 2. the factories --------------------------------------------------------

$factBanner = @(
    '// GENERATED by tools/regen_vrchat_table.ps1. Do not edit by hand.',
    ''
)
Set-Content -LiteralPath $factOut -Value (($factBanner + $sections['factories']) -join "`n") -NoNewline

# --- 3. include them from the hand-written table -----------------------------

$tableText = Get-Content -LiteralPath $table -Raw
$anchor = '} // namespace VrcGenerated'
if ($tableText -notmatch [regex]::Escape($anchor)) { throw "table anchor not found: $anchor" }
if ($tableText -notmatch 'vrchat_generated_types\.inl') {
    $tableText = $tableText.Replace($anchor, "#include `"vrchat_generated_types.inl`"`n$anchor")
    Set-Content -LiteralPath $table -Value $tableText -NoNewline
    Write-Output 'added types include to the table'
}

# The enum table has to be visible before the emitter's IsManagedEnum compiles,
# so it is included from mod_project_generator_vrchat.inl rather than the table.
$vrchatInl = "$Repo\src\sdk\templates\mod_project_generator_vrchat.inl"
$vrchatText = Get-Content -LiteralPath $vrchatInl -Raw
if ($vrchatText -notmatch 'vrchat_generated_enums\.inl') {
    $vrchatText = $vrchatText.Replace(
        '#include "VRChat/vrchat_generated_emit.inl"',
        "#include `"VRChat/vrchat_generated_enums.inl`"`n#include `"VRChat/vrchat_generated_emit.inl`"")
    Set-Content -LiteralPath $vrchatInl -Value $vrchatText -NoNewline
    Write-Output 'added enums include ahead of the emitter'
}

$factAnchor = 'namespace {'
if ($tableText -notmatch 'vrchat_generated_factories\.inl') {
    $tableText = Get-Content -LiteralPath $table -Raw
    $idx = $tableText.LastIndexOf($factAnchor)
    if ($idx -lt 0) { throw 'no anonymous namespace in the table' }
    $tableText = $tableText.Insert($idx, "#include `"vrchat_generated_factories.inl`"`n`n")
    Set-Content -LiteralPath $table -Value $tableText -NoNewline
    Write-Output 'added factories include to the table'
}

# --- 4. splice the write list into the generator -----------------------------

$commonText = Get-Content -LiteralPath $common -Raw
# The hand-written rows are clang-formatted, so the VRCLogger row is wrapped
# across lines and the anchor has to be whitespace insensitive.
$anchorRx = [regex]'(?s)(\{"sdk/VRChat/VRC/Core/VRCLogger\.h".*?VRChatGeneratedVrcLogger\(\), true,\s*true\},)'
if (-not $anchorRx.IsMatch($commonText)) { throw 'write-list anchor not found (VRCLogger row)' }
$begin = '// >>> VRCHAT_GENERATED_WRITES >>>'
$end   = '// <<< VRCHAT_GENERATED_WRITES <<<'
$block = "$begin`n" + $sections['writes'] + "`n$end"

if ($commonText -notmatch 'VRCHAT_GENERATED_WRITES') {
    $commonText = $anchorRx.Replace($commonText, "`$1`n`n$block", 1)
    Set-Content -LiteralPath $common -Value $commonText -NoNewline
    Write-Output 'spliced write list into the generator'
} else {
    $rebuilt = "$begin`n" + $sections['writes'] + "`n$end"
    $commonText = [regex]::Replace(
        $commonText, '(?s)// >>> VRCHAT_GENERATED_WRITES >>>.*?// <<< VRCHAT_GENERATED_WRITES <<<', $rebuilt)
    Set-Content -LiteralPath $common -Value $commonText -NoNewline
    Write-Output 'refreshed write list in the generator'
}

# --- report ------------------------------------------------------------------

Write-Output ''
Write-Output "  $typesOut"
Write-Output "  $factOut"
Write-Output "  $common  (write list)"
$opaque  = @($err | Where-Object { $_ -match '^(System|Unity|VRC|Il2Cpp)\.' }).Count
Write-Output "  member types emitted as void*: $opaque"
